Repository today-zipsa/TodayZipsa, pull requests merged in 2023-02, with the labels that each got.

#33 feat: 마이페이지 html 구조 및 profile-container 레이아웃 작업
  src/api/my-dummy.js
  src/asset/profile.png
  src/modules/my.js
  src/pages/my.html
  src/styles/my.css
Labels: enhancement

#38 [join] 레이아웃 구현#25
  src/asset/check.svg
  src/pages/join.html
  src/styles/join.css
Labels: enhancement

#39 fix: Payment Page PR
  src/modules/payment1.js
  src/modules/payment2.js
  src/pages/payment1.html
  src/pages/payment2.html
  src/styles/payment1.css
Labels: enhancement

#44 fix: 회원가입 레이아웃 구현#25
  src/pages/join.html
  src/styles/join.css
Labels: enhancement

#50 [Feat] 결제내역 및 계좌 관리 퍼블리싱 및 Navigo Router 초기 환경 셋팅
  index.html
  package-lock.json
  package.json
  src/api/my_accounts_dummy.js
  src/api/my_payment_dummy.js
  src/api/my_usable_banks_dummy.js
  src/asset/bankImg/hana_bank.png
  src/asset/bankImg/k_bank.png
  src/asset/bankImg/kakao_bank.png
  src/asset/bankImg/kb_bank.png
  src/asset/bankImg/nh_bank.png
  src/asset/bankImg/sh_bank.png
  src/asset/bankImg/woori_bank.png
  src/asset/btnImg/add_btn.png
  src/asset/btnImg/close_btn.png
  src/asset/btnImg/search_btn.png
  src/asset/global/main-logo.png
  src/asset/global/no_image.png
  src/asset/myImg/profile.png
  src/modules/my.js
  src/modules/router.js
  src/pages/home.js
  src/pages/my.html
  src/pages/my_order_detail.html
  src/pages/my_payment_detail.html
  src/styles/header.css
  src/styles/home.css
  src/styles/home.scss
  src/styles/main.scss
  src/styles/my.css
  src/styles/my.scss
Labels: enhancement

#51 [Fix] index.html에 연결된 javascript 파일경로 수정
  index.html
Labels: bug

#53 feat: util.js에 createEl 함수추가(feature/feat#52)
  src/api/util.js
Labels: enhancement

#49 feat: 공통 footer 구현 feat#27/ Issue #29
  src/asset/facebook.svg
  src/asset/instagram.svg
  src/asset/twitter.svg
  src/modules/footer.js
  src/pages/login.html
  src/styles/login.css
Labels: enhancement

#61 feat: 렌더링 로직 수정 및 공통헤더&마이페이지 리팩토링
  index.html
  src/components/pages/myPage.js
  src/components/templates/header.js
  src/modules/router.js
  src/pages/my.html
  src/styles/header.css
  src/styles/header.scss
  src/styles/main.css
  src/styles/main.scss
  src/styles/my.css
  src/styles/my.scss
Labels: enhancement

#66 fix: my.js 타입에러 처리 및 레이아웃 깨짐 현상 해결
  index.html
  src/modules/my.js
  src/styles/main.css
Labels: bug

#71 fix: main.scss -> index.scss로 파일명 변경으로 인한 index.html css 참조 경로 수정
  index.html
Labels: bug

#79 fix: 공통헤더 CSS 경로 수정
  src/styles/index.scss
Labels: bug, enhancement

#65 feat: login page #27
  src/components/pages/loginPage.js
  src/modules/router.js
  src/pages/join.html
  src/pages/login.html
  src/styles/index.css
  src/styles/join.css
  src/styles/login.css
  src/styles/main.css
Labels: enhancement

#94 fix: 오늘의 집사 배포 2.0 에러 해결 및 기타 버그 해결
  index.html
  package-lock.json
  package.json
  src/components/pages/footer.js
  src/components/pages/joinPage.js
  src/components/pages/loginPage.js
  src/components/pages/mainPage.js
  src/components/pages/myPage.js
  src/components/templates/modal.js
  src/components/templates/modalTwo.js
  src/modules/admin.js
  src/modules/mainPage.js
  src/modules/modal_templates.js
  src/modules/my.js
  src/modules/router.js
  src/pages/detail.html
  src/pages/rental.html
  src/pages/sitters.html
  src/styles/admin.css
  src/styles/index.css
  src/styles/login.css
  src/styles/my.css
  src/styles/my.scss
Labels: bug, enhancement

#85 feat: 회원가입 레이아웃, 로직 #26
  index.html
  package-lock.json
  src/api/common.js
  src/asset/global/check_green.svg
  src/components/pages/joinPage.js
  src/modules/join.js
  src/modules/router.js
  src/pages/joinPage.js
  src/styles/join.css
Labels: enhancement

#106 fix: 결재/결재완료/어드민/로그인/회원가입 페이지 렌더링 로직 리팩토링
  .gitignore
  index.html
  package-lock.json
  src/components/pages/adminPage.js
  src/components/pages/joinPage.js
  src/components/pages/loginPage.js
  src/components/pages/myPage.js
  src/components/pages/paymentDonePage.js
  src/components/pages/paymentPage.js
  src/modules/admin.js
  src/modules/join.js
  src/modules/my.js
  src/modules/payment1.js
  src/modules/payment2.js
  src/modules/router.js
  src/pages/detail.html
  src/pages/payment.html
  src/pages/payment2.html
  src/pages/paymentDone.html
  src/pages/sitters.html
  src/styles/admin.css
  src/styles/home.css
  src/styles/home.scss
  src/styles/index.scss
  src/styles/main.css
  src/styles/payment.css
  src/styles/paymentDone.css
Labels: bug

#97 feat:로그인, footer 변경사항 #27
  src/components/pages/joinPage.js
  src/components/pages/loginPage.js
  src/modules/login.js
  src/styles/index.css
  src/styles/index.scss
  src/styles/join.css
  src/styles/login.css
Labels: enhancement

#115 feat: 공통헤더 로그인/로그아웃 기능 구현 및 마이페이지/어드민 페이지 라우팅 추가
  src/components/templates/header.js
  src/styles/header.css
  src/styles/header.scss
  src/styles/index.css
  src/styles/index.scss
Labels: enhancement

#113 [Feat] 메인 페이지 작업 #107
  index.html
  src/components/pages/homePage.js
  src/modules/admin.js
  src/modules/home.js
  src/modules/router.js
  src/styles/admin.css
  src/styles/home.css
Labels: enhancement

#116 feat: index.scss에 메인페이지 css파일 모듈 @import 추가 #112
  src/styles/home.css
  src/styles/hotel.css
  src/styles/index.css
  src/styles/index.scss
  src/styles/main.css
  src/styles/main.scss
Labels: enhancement
