Repository today-zipsa/TodayZipsa, pull requests merged in 2023-03, with the labels that each got.

#127 feat: 회원가입 페이지 필수요구사항 기능 구현 #26
  index.html
  src/components/pages/joinPage.js
  src/modules/admin.js
  src/modules/join.js
  src/modules/router.js
  src/styles/footer.scss
  src/styles/join.css
  src/styles/join.scss
  src/styles/login.scss
  src/styles/main.css
  src/styles/my.css
Labels: bug, enhancement

#128 [Feat] 카테고리별 화면 구현 #125
  index.html
  src/components/pages/categoryPage.js
  src/modules/admin.js
  src/modules/category.js
  src/modules/router.js
  src/styles/category.css
  src/styles/home.css
Labels: enhancement

#131 [Design] 회원가입페이지: 약관동의, 프로필사진 수정 #130
  src/components/pages/joinPage.js
  src/modules/join.js
  src/styles/join.css
  src/styles/join.scss
Labels: enhancement

#135 [Fix] 카테고리 문구 수정 (차량->렌트카) (이슈#134)
  src/components/pages/adminPage.js
  src/components/pages/categoryPage.js
  src/components/pages/homePage.js
  src/modules/admin.js
  src/modules/category.js
  src/modules/home.js
  src/modules/router.js
Labels: bug

#138 feat: 마이페이지 계좌관리 기능 일부 구현
  src/components/pages/myPage.js
  src/modules/modal_templates.js
  src/modules/my.js
  src/modules/router.js
  src/styles/home.css
  src/styles/index.scss
Labels: enhancement

#140 fix: 로그인 기능 에러 해결 작업완료
  src/modules/login.js
  src/modules/router.js
Labels: bug

#142 fix: 로그아웃 된 후 '로그아웃' 버튼 노출 에러 및 로컬스토리지에 유저 정보 저장 누락 문제
  index.html
  src/components/templates/header.js
  src/modules/login.js
Labels: bug

#143 fix: 회원가입 프로필 추가 로직 수정 및 password value 누락 수정#133
  src/components/pages/joinPage.js
  src/modules/join.js
  src/modules/router.js
  src/styles/index.scss
  src/styles/join.css
  src/styles/join.scss
Labels: bug, enhancement

#144 [Feat] 상세페이지 연결
  src/components/pages/detailPage.js
  src/modules/router.js
Labels: enhancement

#157 feat: join.js 파일 충돌 해결 및 static routing 환경 설정
  .gitignore
  config/_redirects
  package.json
  src/modules/admin.js
Labels: bug, enhancement

#159 fix: IC_chip 버튼 경로 설정 오류
  package.json
  src/asset/bankImg/IC_chip.png
  src/modules/my.js
Labels: bug

#169 feat: 라우팅 수정 및 메타태그 추가 작업과 404/어드민/제품 상세 페이지 관련 기능 구현 및 퍼블리싱
  favicon.ico
  index.html
  src/api/common.js
  src/asset/global/favicon.png
  src/asset/global/sad_kitty.png
  src/components/pages/404Page.js
  src/components/pages/adminPage.js
  src/components/pages/detailPage.js
  src/components/pages/homePage.js
  src/components/pages/mainPage.js
  src/components/pages/paymentDonePage.js
  src/components/pages/paymentPage.js
  src/components/pages/searchPage.js
  src/components/templates/header.js
  src/modules/404.js
  src/modules/admin.js
  src/modules/detailPage.js
  src/modules/home.js
  src/modules/index.js
  src/modules/main.js
  src/modules/search.js
  src/styles/404.scss
  src/styles/admin.css
  src/styles/detail.scss
  src/styles/home.css
  src/styles/home.scss
  src/styles/index.scss
Labels: enhancement

#170 feat: package.json 파일 수정 및 라우팅/css 모듈 추가 작업
  package.json
  src/modules/index.js
  src/styles/index.scss
Labels: enhancement

#173 feat: 마이페이지 유효한 계좌 체크 로직 에러 #171
  src/modules/index.js
  src/modules/my.js
Labels: bug

#175 feat: 마이페이지 프로필 수정 모달창 기능 구현 및 결재내역 조회 데이터 바인딩 및 공통헤더 버그 수정
  src/components/pages/myPage.js
  src/components/templates/header.js
  src/modules/index.js
  src/modules/my.js
  src/styles/my.scss
Labels: bug, enhancement

#180 feat: 오늘의 집사 v1.1 배포
  src/asset/btnImg/next_btn.png
  src/asset/btnImg/prev_btn.png
  src/components/pages/adminPage.js
  src/components/pages/myPage.js
  src/modules/admin.js
  src/modules/login.js
  src/modules/my.js
  src/styles/404.scss
  src/styles/admin.css
  src/styles/my.scss
Labels: bug, enhancement

#182 feat: 마이페이지 구매내역 페이징처리 관련 스크롤이벤트 로직 추가 및 썸네일 이미지 바인딩 #181
  src/components/pages/myPage.js
  src/modules/my.js
Labels: enhancement

#184 fix: 공통헤더 검색창에서 키워드 검색후 상품클릭시 라우팅 주소 오류 현상 #183
  src/components/pages/myPage.js
  src/modules/search.js
Labels: bug

#186 feat: .gitignore 파일 수정 및 package-lock.json gitignore 반영 안되는 이슈 해결
  .gitignore
  src/components/pages/myPage.js
Labels: bug, enhancement
